indussh/main/routes.py
from flask import render_template, redirect, url_for, Blueprint, request, session
from indussh.models import Product

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def index():
    return render_template('index.html')

@main.route('/about')
def about():
    return render_template('about.html')

@main.route('/contact')
def contact():
    return render_template('contact.html')

indussh/products/routes.py
from flask import render_template, redirect, url_for, Blueprint, request, session, jsonify
from indussh.models import Product, Customer, Order, OrderItem
from indussh.products.forms import BillingForm
from indussh.products.recommender import Recommender
from indussh import db
import pandas as pd

products = Blueprint('products', __name__)

@products.route('/')
def shop():
    page = request.args.get('page', 1, type=int)
    categories = [c[0] for c in Product.query.with_entities(Product.category).distinct()]
    types={}
    for category in categories:
        types[category] = [t[0] for t in Product.query.filter_by(category=category).with_entities(Product.type).distinct()]
    
    products = Product.query.order_by(Product.added_on.desc()).paginate(page=page, per_page=9)

    return render_template('shop.html', products=products, categories=categories, types=types)

@products.route('/product/<string:article_no>')
def shop_single(article_no):
    # Get the product data
    product = Product.query.filter_by(article_no=article_no).first()
    # Get the recommendations for the product
    recommendations = get_product_recommendations(article_no=article_no)

    return render_template('shop-single.html', product=product, recommendations=recommendations)

def get_product_recommendations(article_no):
    # Get the sql query
    sql = db.session.query(Product).with_entities(Product.id, 
                                                    Product.article_no, 
                                                    Product.name, 
                                                    Product.description,
                                                    Product.type,
                                                    Product.category).statement
    # Read the data from database using pandas
    prods = pd.read_sql(sql, db.session.bind)

    # Extract and combine the features for the recommendation system
    prods['details'] = prods['name'] + ' ' + prods['category'] + ' ' + prods['type'] + ' ' + prods['description']
    # Drop the columns after extracting the features
    prods.drop(['name', 'category', 'type', 'description'], axis=1, inplace=True)
    # Initialize the recommender instance
    recommender = Recommender(prods)
    # Get recommendation results
    recommendation_results = recommender.recommend(article_no, 10)
    # Get Article no's of recommended products
    rec_prods_nos = [rec[1] for rec in recommendation_results]

    return Product.query.filter(Product.article_no.in_(rec_prods_nos)).all()

@products.route('/<string:category>')
def shop_by_category(category):
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter_by(category=category).order_by(Product.added_on.desc()).paginate(page=page, per_page=9)
    types=[]
    types = [t[0] for t in Product.query.filter_by(category=category).with_entities(Product.type).distinct()]
    return render_template('shop-by-category.html', products=products, category=category, types=types)

@products.route('/<string:category>/<string:type>')
def shop_by_type(category, type):
    page = request.args.get('page', 1, type=int)
    products = Product.query.filter_by(category=category, type=type).order_by(Product.added_on.desc()).paginate(page=page, per_page=9)
    types=[]
    types = [t[0] for t in Product.query.filter_by(category=category).with_entities(Product.type).distinct()]
    return render_template('shop-by-type.html', products=products, type=type, category=category, types=types)

@products.route('/addtocart', methods=['POST'])
def add_to_cart():
    article_no = request.form['article_no']
    size_selected = request.form['size']
    quantity = int(request.form['quantity'])
    
    if 'discount_price' in session:
        disc_price = session['discount_price']
    else:
        disc_price = 0

    if size_selected and quantity and size_selected != 'nosize' and quantity > 0:
        # Cart Session Starts here
        if 'cart' in session:
            # if product is not in the cart then add it
            if not any(article_no in p for p in session['cart']):
                session['cart'].update({article_no: [quantity, size_selected, disc_price]})
                return jsonify({'success': 'Product added to cart!'})
            # if the product is already in the cart, update the quantity
            elif any(article_no in p for p in session['cart']):
                session['cart'][str(article_no)][0] += quantity
                return jsonify({'success': 'Product already in the cart so quantity updated!'})
        else:
            # start the cart if already not created and add the product in it.
            session['cart'] = { article_no: [quantity, size_selected, disc_price] }
            return jsonify({'success': 'Product added to cart!'})
   
    return jsonify({'error': 'Please select size and quantity'})

@products.route('/cart')
def cart():
    cart_prods = []
    if 'cart' in session:
        cart_prods = list(session['cart'].keys())
        products = Product.query.filter(Product.article_no.in_(cart_prods)).all()
        total = int(calculate_total_amount(products))
        return render_template('cart.html', products=products, total=total)
    return render_template('cart.html')

def calculate_total_amount(products):
    cart_products = session['cart']
    total_amount = 0
    for product in products:
        if product.article_no in cart_products:
            article_no = product.article_no
            quantity = cart_products[article_no][0]
            # app.logger.info(p)
            if cart_products[article_no][2] != 0:
                price = cart_products[article_no][2]
            else:
                price  = product.price
                
            total_amount += (int(quantity) * int(price))
    
    return total_amount
    # session.pop('discount_price', None)

@products.route('/removecartitem/<string:article_no>')
def remove_from_cart(article_no):
    if article_no in session['cart']:
        session['cart'].pop(article_no)
        if len(session['cart'].items()) <= 0:
            session.clear()
        return redirect(url_for('products.cart'))


@products.route('/checkout', methods=['GET', 'POST'])
def checkout():
     if 'cart' in session:
        cart_prods = list(session['cart'].keys())
        products = Product.query.filter(Product.article_no.in_(cart_prods)).all()
        total = int(calculate_total_amount(products))

        form = BillingForm()

        if form.validate_on_submit():
            
            customer = Customer(name=form.name.data,
                                address=form.address.data,
                                city=form.city.data,
                                postcode=form.postcode.data,
                                email=form.email.data,
                                phone_number=form.phone_number.data
                                )
            db.session.add(customer)
            db.session.commit()

            # Create an order
            order = Order(amount=total, customer_id=customer.id, notes=form.notes.data)
            db.session.add(order)

            # Add the items in order items
            for article_no in cart_prods:
                product = Product.query.filter_by(article_no=article_no).first()
                order_item = OrderItem(quantity=session['cart'][str(article_no)][0], 
                                        discounted_price=session['cart'][str(article_no)][2],
                                        product_id=product.id,
                                        order_id=order.id
                                        )
                db.session.add(order_item)
            
            db.session.commit()
            session.clear()
            return redirect(url_for('products.thanks'))
            
        return render_template('checkout.html', products=products, total=total, form=form)


@products.route('/completed')
def thanks():
    return render_template('thankyou.html')

@products.route('/shop/search-results', methods=['GET', 'POST'])
def search():
    page = request.args.get('page', 1, type=int)
    
    if request.method == 'POST':
        search_query = request.form.get('search-query')
        session['search-query'] = search_query
    elif 'search-query' in session:
        search_query = session['search-query']

    products = Product.query.filter(Product.name.like('%' + search_query + '%')).paginate(page=page, per_page=9)
    results_count = Product.query.filter(Product.name.like('%' + search_query + '%')).count()
    
    return render_template('search-results.html', search_query=search_query, products=products, results_count=results_count)

indussh/templates/cart.html
{% extends 'layout.html' %}
{% set total_amount = 0 %}
{% block body %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{{ url_for('main.index') }}">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Cart</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">
        <div class="row mb-5">
          <div class="col-md-12">
            <div class="site-blocks-table">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <th class="product-thumbnail">Image</th>
                    <th class="product-name">Product</th>
                    <th class="product-name">Size</th>
                    <th class="product-price">Price</th>
                    <th class="product-price">Disc. Price</th>
                    <th class="product-quantity">Quantity</th>
                    <th class="product-total">Total</th>
                    <th class="product-remove">Remove</th>
                  </tr>
                </thead>
                <tbody>
                  {% for product in products %}
                        <tr>
                          <td class="product-thumbnail">
                            <img src="{{ url_for('static', filename='uploads/product_images/'+product.image_file) }}" alt="Image" class="img-fluid">
                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">{{ product.name }}</h2>
                          </td>
                          <td>{{ session.cart[product.article_no][1]|title }}</td>
                          <td>{{ product.price }}</td>
                          <td>
                            <!-- discounted price -->
                              {{ session.cart[product.article_no][2] }}
                          </td>
                          <!-- QUANTITY -->
                          <td>{{ session.cart[product.article_no][0] }}</td>
                          <!-- QUANTITY * PRICE -->
                          {% if session.cart[product.article_no][2]|int != 0 %}
                            <td>{{ session.cart[product.article_no][0]|int * session.cart[product.article_no][2]|int }}</td>
                          {% else %}
                            <td>{{ session.cart[product.article_no][0]|int * product.price|int }}</td>
                          {% endif %}
                          <td>
                            <!-- <form id="remove_item" action="{{url_for('products.remove_from_cart', article_no=product.article_no)}}" method="POST">
                              <input type="hidden" name="_method" value="DELETE">
                              <input type="submit" class="btn btn-danger btn-sm" value="X" >
                            </form> -->
                            <a class="btn btn-danger btn-sm" role="button" href="{{url_for('products.remove_from_cart', article_no=product.article_no)}}">X</a>
                          </td>
                        </tr>
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col-md-6">
            <div class="row mb-5">
              <div class="col-md-6">
                <a href="{{ url_for('products.shop') }}" class="btn btn-outline-primary btn-sm btn-block">Continue Shopping</a>
              </div>
            </div>
            <!-- <div class="row">
              <div class="col-md-12">
                <label class="text-black h4" for="coupon">Coupon</label>
                <p>Enter your coupon code if you have one.</p>
              </div>
              <div class="col-md-8 mb-3 mb-md-0">
                <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
              </div>
              <div class="col-md-4">
                <button class="btn btn-primary btn-sm">Apply Coupon</button>
              </div>
            </div> -->
          </div>
          {% if session.cart|length > 0 %}
            <div class="col-md-6 pl-5">
              <div class="row justify-content-end">
                <div class="col-md-7">
                  <div class="row">
                    <div class="col-md-12 text-right border-bottom mb-5">
                      <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                    </div>
                  </div>
                  <div class="row mb-3">
                    <div class="col-md-6">
                      <span class="text-black">Subtotal</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">Rs. {{ total }}</strong>
                    </div>
                  </div>
                  <div class="row mb-5">
                    <div class="col-md-6">
                      <span class="text-black">Total</span>
                    </div>
                    <div class="col-md-6 text-right">
                      <strong class="text-black">Rs. {{ total }}</strong>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-md-12">
                      <a href="{{ url_for('products.checkout') }}" class="btn btn-primary btn-lg py-3 btn-block">Proceed To Checkout</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>

{% endblock %}

indussh/templates/search-results.html
{% extends 'layout.html' %}
{% set active_page = 'shop' %}
{% block body %}

    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{{ url_for('main.index') }}">Home</a><span class="mx-2 mb-0">/</span><strong class="text-black">Search</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">

        <div class="row mb-5">
          <div class="col-md-12 order-2">

            <div class="row">
              <div class="col-md-12 mb-5">
                <div class="float-md-left mb-4"><h2 class="text-black h5">Found {{ results_count }} search result(s) for {{ search_query }}</h2></div>
              </div>
            </div>
          <div class="row mb-5">
            {% for product in products.items %}
              <div class="col-sm-6 col-lg-4 mb-4" data-aos="fade-up">
                <div class="block-4 text-center border">
                  <!-- <small class="mb-0 text-default">Product no: {{ product.article_no }}</small> -->
                  <figure class="block-4-image">
                    <a href="{{ url_for('products.shop_single', article_no = product.article_no )}}"><img src="{{ url_for('static', filename='uploads/product_images/'+product.image_file) }}" alt="Image placeholder" class="img-fluid"></a>
                  </figure>
                  <div class="block-4-text p-4">
                    <h6><a href="{{ url_for('products.shop_single', article_no = product.article_no )}}">{{ product.name }}</a></h6>
                    <p class="mb-0"></p>
                    <p class="text-danger font-weight-bold"><span class="icon icon-tag"></span>Rs. {{product.price}}/-</p>

                    <a href="{{ url_for('products.shop_single', article_no = product.article_no )}}" class="btn btn-primary btn-icon-split btn-sm">
                      <span class="icon text-white-50">
                        <i class="fas fa-shopping-bag"></i>
                      </span>
                      <span class="text">Bargain and Buy</span>
                    </a>
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>

          <div class="row" data-aos="fade-up">
            <div class="col-md-12 text-center">
              <div class="site-block-27">
                <ul>
                    {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=4) %}
                      {% if page_num %}
                        {% if products.page == page_num %}
                          <a class="btn btn-primary mb-4" href="{{ url_for('products.search', page=page_num) }}">{{ page_num }}</a>
                        {% else %}
                          <a class="btn btn-outline-primary mb-4" href="{{ url_for('products.search', page=page_num) }}">{{ page_num }}</a>
                        {% endif %}
                      {% else %}
                        ...
                      {% endif %}
                    {% endfor %}
                </ul>
              </div>
            </div>
          </div>
            
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="site-section site-blocks-2">
                <div class="row justify-content-center text-center mb-5">
                  <div class="col-md-7 site-section-heading pt-4">
                    <h2>Categories</h2>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                    <a class="block-2-item" href="#">
                      <figure class="image">
                        <img src="../static/images/women.jpg" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Women</h3>
                      </div>
                    </a>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
                    <a class="block-2-item" href="#">
                      <figure class="image">
                        <img src="../static/images/men.jpg" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Men</h3>
                      </div>
                    </a>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                    <a class="block-2-item" href="#">
                      <figure class="image">
                        <img src="../static/images/boys.jpg" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Boys</h3>
                      </div>
                    </a>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                    <a class="block-2-item" href="#">
                      <figure class="image">
                        <img src="../static/images/girls.jpg" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Girls</h3>
                      </div>
                    </a>
                  </div>
                </div>
              
            </div>
          </div>
        </div>
        
      </div>
    </div>

{% endblock %}

indussh/templates/shop.html
{% extends 'layout.html' %}
{% set active_page = 'shop' %}
{% block body %}
    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="{{ url_for('main.index') }}">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Shop</strong></div>
        </div>
      </div>
    </div>

    <div class="site-section">
      <div class="container">

        <div class="row mb-5">
          <div class="col-md-9 order-2">

            <div class="row">
              <div class="col-md-12 mb-5">
                <div class="float-md-left mb-4"><h2 class="text-black h5">Shop All</h2></div>
                <div class="d-flex">
                  <div class="dropdown mr-1 ml-md-auto">
                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" id="dropdownMenuOffset" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Latest
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuOffset">
                      <a class="dropdown-item" href="{{ url_for('products.shop_by_category', category='men') }}">Men</a>
                      <a class="dropdown-item" href="{{ url_for('products.shop_by_category', category='women') }}">Women</a>
                      <a class="dropdown-item" href="{{ url_for('products.shop_by_category', category='boys') }}">Boys</a>
                      <a class="dropdown-item" href="{{ url_for('products.shop_by_category', category='girls') }}">Girls</a>
                    </div>
                  </div>
                  <div class="btn-group">
                    <button type="button" class="btn btn-secondary btn-sm dropdown-toggle" id="dropdownMenuReference" data-toggle="dropdown">Reference</button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
                      <a class="dropdown-item" href="#">Relevance</a>
                      <a class="dropdown-item" href="#">Name, A to Z</a>
                      <a class="dropdown-item" href="#">Name, Z to A</a>
                      <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="#">Price, low to high</a>
                      <a class="dropdown-item" href="#">Price, high to low</a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <div class="row mb-5">

            {% for product in products.items %}
              <div class="col-sm-8 col-lg-4 mb-4" data-aos="fade-up">
                <div class="block-4 text-center border">
                    <!-- <small class="mb-0">Product no: {{ product.article_no }}</small> -->
                  <figure class="block-4-image">
                    <a href="{{ url_for('products.shop_single', article_no = product.article_no )}}"><img src="{{ url_for('static', filename='uploads/product_images/'+product.image_file) }}" alt="{{ product.name }}" class="img-fluid"></a>
                  </figure>
                  <div class="block-4-text p-4">
                    
                    <h6><a href="{{ url_for('products.shop_single', article_no = product.article_no )}}">{{ product.name }}</a></h6>
                    <p class="text-danger font-weight-bold"><span class="icon icon-tag"></span>Rs. {{ product.price }}/-</p>

                    <a href="{{ url_for('products.shop_single', article_no = product.article_no )}}" class="btn btn-primary btn-icon-split btn-sm">
                        <span class="icon text-white-50">
                          <i class="fas fa-shopping-bag"></i>
                        </span>
                        <span class="text">Bargain and Buy</span>
                    </a>
                
                  </div>
                </div>
              </div>
            {% endfor %}
          </div>

          <div class="row" data-aos="fade-up">
              <div class="col-md-12 text-center">
                <div class="site-block-27">
                  <ul>
                      {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=4) %}
                        {% if page_num %}
                          {% if products.page == page_num %}
                            <a class="btn btn-primary mb-4" href="{{ url_for('products.shop', page=page_num) }}">{{ page_num }}</a>
                          {% else %}
                            <a class="btn btn-outline-primary mb-4" href="{{ url_for('products.shop', page=page_num) }}">{{ page_num }}</a>
                          {% endif %}
                        {% else %}
                          ...
                        {% endif %}
                      {% endfor %}
                  </ul>
                </div>
              </div>
            </div>
            
          </div>

          <div class="col-md-3 order-1 mb-5 mb-md-0">
            <div class="border p-4 rounded mb-4">
              <h3 class="mb-3 h6 text-uppercase text-black d-block">Categories</h3>
              <ul class="list-unstyled mb-0">
                {% for category in categories %}
                <li class="mb-1">
                  <a href="{{ url_for('products.shop_by_category', category=category) }}" class="d-flex">
                    <span>{{ category|title }}</span> 
                    <span class="text-black ml-auto">
                    </span>
                  </a>
                </li>
                {% endfor %}
              </ul>
            </div>

            <div class="border p-4 rounded mb-4">
             {% for category in categories %}
              <div class="mb-4">
                <h3 class="mb-3 h6 text-uppercase text-black d-block">{{ category|title }}</h3>
                {% for type in types[category] %}
                  <a href="{{ url_for('products.shop_by_type', category='men', type=type) }}" class="d-flex color-item align-items-center" >
                    <span style="color: lightcoral;" class="far fa-arrow-alt-circle-right"></span>&nbsp;&nbsp; <span>{{ type|title }}</span>
                  </a>
                {% endfor %}
              </div>
              <hr>
              {% endfor %}
            </div>
            
          </div>
        </div>

        <div class="row">
          <div class="col-md-12">
            <div class="site-section site-blocks-2">
                <div class="row justify-content-center text-center mb-5">
                  <div class="col-md-7 site-section-heading pt-4">
                    <h2>Categories</h2>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-4 mb-lg-0" data-aos="fade" data-aos-delay="">
                    <a class="block-2-item" href="{{ url_for('products.shop_by_category', category='women') }}">
                      <figure class="image">
                        <img src="{{ url_for('static', filename='images/women.jpg') }}" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Women</h3>
                      </div>
                    </a>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="200">
                    <a class="block-2-item" href="{{ url_for('products.shop_by_category', category='men') }}">
                      <figure class="image">
                        <img src="{{ url_for('static', filename='images/men.jpg') }}" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Men</h3>
                      </div>
                    </a>
                  </div>
                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                    <a class="block-2-item" href="{{ url_for('products.shop_by_category', category='boys') }}">
                      <figure class="image">
                        <img src="{{ url_for('static', filename='images/boys.jpg') }}" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Boys</h3>
                      </div>
                    </a>
                  </div>

                  <div class="col-sm-6 col-md-6 col-lg-3 mb-5 mb-lg-0" data-aos="fade" data-aos-delay="100">
                    <a class="block-2-item" href="{{ url_for('products.shop_by_category', category='girls') }}">
                      <figure class="image">
                        <img src="{{ url_for('static', filename='images/girls.jpg') }}" alt="" class="img-fluid">
                      </figure>
                      <div class="text">
                        <span class="text-uppercase">Collections</span>
                        <h3>Girls</h3>
                      </div>
                    </a>
                  </div>
                </div>
              
            </div>
          </div>
        </div>
        
      </div>
    </div>

{% endblock %}

indussh/templates/thankyou.html
{% extends 'layout.html' %}

{% block body %}
    <div class="bg-light py-3">
      <div class="container">
        <div class="row">
          <div class="col-md-12 mb-0"><a href="index.html">Home</a> <span class="mx-2 mb-0">/</span> <strong class="text-black">Contact</strong></div>
        </div>
      </div>
    </div>  

    <div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <span class="icon-check_circle display-3 text-success"></span>
            <h2 class="display-3 text-black">Thank you!</h2>
            <p class="lead mb-5">You order was successfully placed.</p>
            <p><a href="{{ url_for('products.shop') }}" class="btn btn-sm btn-primary">Back to shop</a></p>
          </div>
        </div>
      </div>
    </div>

{% endblock %}